# This yaml only pushes the code to the existing lambda. You must create
#  the lambda function(s) in the AWS Console first, before triggering the pipeline. 
# Source:  https://www.whitespectre.com/ideas/multiple-aws-lambda-deployment-with-github-actions/ 
on:
  push:
    branches:
      - hw06-main
jobs:
  deploy:
    name: Deploy lambda code
    # Your repo MUST be in a UConn GitHub Organization that has been configured with RH Runners. 
    # This is a manual task that needs to be completed by the UConn School of Business IT staff.
    # The runs-on value must be "self-hosted" to leverage the runner .
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
          
      # Setp AWS CLI
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Zip and deploy 1st lambda function
      - run: | 
          zip -j lambda1.zip ./hw06/lambda/list_buckets.py
          aws lambda update-function-code --function-name=hw06-list-buckets --zip-file=fileb://lambda1.zip
          
      # Zip and deploy 2nd lambda function
      - run: | 
          zip -j lambda2.zip ./hw06/lambda/get_bucket_objects.py
          aws lambda update-function-code --function-name=hw06-get-bucket-objects --zip-file=fileb://lambda2.zip
          
      # Zip and deploy 3rd lambda function
      - run: | 
          zip -j lambda3.zip ./hw06/lambda/add_object.py
          aws lambda update-function-code --function-name=hw06-add-object --zip-file=fileb://lambda3.zip
        
      # Zip and deploy 4th lambda function
      - run: | 
          zip -j lambda4.zip ./hw06/lambda/delete_object.py
          aws lambda update-function-code --function-name=hw06-delete-object --zip-file=fileb://lambda4.zip
      
  test:
    name: test
    needs: deploy
    runs-on: self-hosted
  
    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f hw06/requirements.txt ]; then pip install -r hw06/requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint hw06/hw06_test_api.py
      - name: Run all your pytest tests in your code
        run: |
          pytest hw06/hw06_test_api.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
